---
title: "This is a Test"
description: | 
  Scientific and technical writing, native to the web
author:
  - first_name: "Nishant"
    last_name: "Aswani"
    url: https://nishantaswani.com
    affiliation: New York University
    affiliation_url: https://www.nyuad.nyu.edu
output: distill::distill_article
---

#### Testing out Math

$$
\sigma = \sqrt{ \frac{1}{N} \sum_{i=1}^N (x_i -\mu)^2}
$$

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

<aside>
This content will appear in the gutter of the article.
</aside>

## Acknowledgments {.appendix}

This is a place to recognize people and institutions. It may also be a good place
to acknowledge and cite software that makes your work possible.

## Author Contributions {.appendix}

We strongly encourage you to include an author contributions statement briefly 
describing what each author did.