on:
  workflow_dispatch:
  push:
    branches: main

name: Render

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies, save github token for gh(), render site
        run: |
          github_token <- "${{ secrets.GITHUB_TOKEN }}"
          install.packages(c("distill", "postcards", "devtools",
          "fs", "htmltools", "here", "magick", "gh", "jsonlite"))
  
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
