name: Render Pages with Distill RMarkdown
on:
  push:
    branches: [main, master]
  workflow_dispatch:
env:
  IMAGE_NAME: distill-docker
  TAG: ghcr.io/niniack/writing/distill-docker:latest
jobs:
  render:

    runs-on: macos-latest

    steps:  

      - uses: actions/checkout@v2
      
      - name: Run docker image
        run: docker run hello-world

      - name: Pull image
        run: docker pull ghcr.io/niniack/writing/distill-docker:latest

      - name: Run docker image
        run: docker run -v ${PWD}:/github/workspace ghcr.io/niniack/writing/distill-docker:latest

      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
