name: Render Pages with Distill RMarkdown
on: [push]
env:
  IMAGE_NAME: distill-docker
  TAG: ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest
jobs:
  render:
  
    runs-on: ubuntu-latest

    steps:  

      - uses: actions/checkout@v2

      - name: Run
        run: docker run -i -v ${{ github.workspace }}:/github/workspace ${{ env.TAG }}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions