name: Render Pages with Distill RMarkdown
on:
  push:
    branches: [main, master]
  workflow_dispatch:
env:
  IMAGE_NAME: distill-docker
  TAG: ghcr.io/niniack/writing/distill-docker:latest
jobs:
  render:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}      
      - name: Pull image
        run: docker pull ghcr.io/niniack/distill-docker:latest
      - name: Run docker image
        run: docker run -i -v ${{ github.workspace }}:/github/workspace ghcr.io/niniack/distill-docker:latest
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Commit files
        run: |
          git add .
          git commit -am "Update articles"
      - name: Push files
        run: git push
