name: Render Pages with Distill RMarkdown
on:
  push:
    branches: [main, master]
  workflow_dispatch:
env:
  IMAGE_NAME: distill-docker
  TAG: ghcr.io/niniack/writing/distill-docker:latest
jobs:
  render:

    runs-on: ubuntu-latest

    steps:  

      - uses: actions/checkout@v2

      - name: Pull image
        run: docker pull ghcr.io/niniack/distill-docker:latest

      - name: Run docker image
        run: docker run -v ${PWD}:/github/workspace ghcr.io/niniack/distill-docker:latest

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
