name: Render Pages with Distill RMarkdown
on:
  push:
    branches: [main, master]
  workflow_dispatch:
env:
  TAG: ghcr.io/niniack/distill-docker:latest
jobs:
  render:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          
      - name: Pull image
        run: docker pull ${{ env.TAG }}
        
      - name: Run docker image
        run: docker run -i -v ${{ github.workspace }}:/github/workspace ${{ env.TAG }}
        
      - name: Commit change
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
