name: Render Pages with Distill RMarkdown
on:
  push:
    branches: [main, master]
  workflow_dispatch:
env:
  IMAGE_NAME: distill-docker
  TAG: ghcr.io/niniack/writing/distill-docker:latest
jobs:
  render:

    runs-on: ubuntu-latest

    steps:  

      - uses: actions/checkout@v2

      - name: Pull image
        run: docker pull ghcr.io/niniack/distill-docker:latest

      - name: Run docker image
        run: docker run -i -v ${{ github.workspace }}:/github/workspace ghcr.io/niniack/distill-docker:latest

      - name: Commit report
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Update articles"
          git push
