name: Render Pages with Distill RMarkdown
on:
  push:
    branches: [main, master]
  workflow_dispatch:
env:
  IMAGE_NAME: distill-docker
  TAG: ghcr.io/niniack/writing/distill-docker:latest
jobs:
  render:

    runs-on: ubuntu-latest

    steps:  

      - uses: actions/checkout@v2
      
      - name: step 1
        ## Reference your environment variables
        run: echo "The API key is:${{github.workspace}}"
      
      - name: step 1
        ## Reference your environment variables
        run: echo "The API key is:${{env.TAG}}" 

      - name: Run
        run: docker run -i -v ${{ github.workspace }}:/github/workspace ${{ env.TAG }}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
