name: Render Pages with Distill RMarkdown
on:
  push:
    branches: [main, master]
  workflow_dispatch:
env:
  IMAGE_NAME: distill-docker
  TAG: ghcr.io/niniack/writing/distill-docker:latest
  CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
  CI_COMMIT_AUTHOR: Continuous Integration
jobs:
  render:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: Pull image
        run: docker pull ghcr.io/niniack/distill-docker:latest
        
      - name: Run docker image
        run: docker run -i -v ${{ github.workspace }}:/github/workspace ghcr.io/niniack/distill-docker:latest
        
      - name: Commit change
        run: |
          git add -A
          git commit -m "Render from docker"
          git push
